### ISSUE TITLE
Panic when add empty strings in listview

### ISSUE THREAD

**Issue by QianNangong** [rodrigocfd/winsafe#85]
I got something like
`thread 'main' panicked at 'Trying to use an unallocated WString buffer.', C:\Users\likeqing\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winsafe-0.0.17\src\kernel\utilities\w_string.rs:405:34
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library\std\src\panicking.rs:593
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library\core\src\panicking.rs:67
   2: enum2$<winsafe::kernel::utilities::w_string::Buffer>::as_mut_ptr
             at C:\Users\likeqing\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winsafe-0.0.17\src\kernel\utilities\w_string.rs:405 
   3: winsafe::kernel::utilities::w_string::WString::as_mut_ptr
             at C:\Users\likeqing\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winsafe-0.0.17\src\kernel\utilities\w_string.rs:107 
   4: winsafe::comctl::structs::impl$11::set_pszText::closure$1
             at C:\Users\likeqing\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winsafe-0.0.17\src\macros\structs.rs:196
   5: enum2$<core::option::Option<ref_mut$<winsafe::kernel::utilities::w_string::WString> > >::map_or<ref_mut$<winsafe::kernel::utilities::w_string::WString>,ptr_mut$<u16>,winsafe::comctl::structs::impl$11::set_pszText::closure_env$1>
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225\library\core\src\option.rs:1133
   6: winsafe::comctl::structs::LVITEM::set_pszText
             at C:\Users\likeqing\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winsafe-0.0.17\src\macros\structs.rs:196
   7: winsafe::gui::native_controls::list_view_item::ListViewItem::set_text
             at C:\Users\likeqing\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winsafe-0.0.17\src\gui\native_controls\list_view_item.rs:207
   8: winsafe::gui::native_controls::list_view_items::impl$0::add::closure$0<alloc::string::String>
             at C:\Users\likeqing\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winsafe-0.0.17\src\gui\native_controls\list_view_items.rs:81
   9: core::iter::traits::iterator::Iterator::for_each::call::closure$0<tuple$<usize,ref$<alloc::string::String> >,winsafe::gui::native_controls::list_view_items::impl$0::add::closure_env$0<alloc::string::String> >
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225\library\core\src\iter\traits\iterator.rs:853
  10: core::iter::adapters::enumerate::impl$1::fold::enumerate::closure$0<ref$<alloc::string::String>,tuple$<>,core::iter::traits::iterator::Iterator::for_each::call::closure_env$0<tuple$<usize,ref$<alloc::string::String> >,winsafe::gui::native_controls::list_v
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225\library\core\src\iter\adapters\enumerate.rs:107
  11: core::iter::traits::iterator::Iterator::fold<core::slice::iter::Iter<alloc::string::String>,tuple$<>,core::iter::adapters::enumerate::impl$1::fold::enumerate::closure_env$0<ref$<alloc::string::String>,tuple$<>,core::iter::traits::iterator::Iterator::for_e
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225\library\core\src\iter\traits\iterator.rs:2481
  12: core::iter::adapters::enumerate::impl$1::fold<core::slice::iter::Iter<alloc::string::String>,tuple$<>,core::iter::traits::iterator::Iterator::for_each::call::closure_env$0<tuple$<usize,ref$<alloc::string::String> >,winsafe::gui::native_controls::list_view
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225\library\core\src\iter\adapters\enumerate.rs:113
  13: core::iter::adapters::skip::impl$1::fold<core::iter::adapters::enumerate::Enumerate<core::slice::iter::Iter<alloc::string::String> >,tuple$<>,core::iter::traits::iterator::Iterator::for_each::call::closure_env$0<tuple$<usize,ref$<alloc::string::String> >,
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225\library\core\src\iter\adapters\skip.rs:127
  14: core::iter::traits::iterator::Iterator::for_each<core::iter::adapters::skip::Skip<core::iter::adapters::enumerate::Enumerate<core::slice::iter::Iter<alloc::string::String> > >,winsafe::gui::native_controls::list_view_items::impl$0::add::closure_env$0<allo
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225\library\core\src\iter\traits\iterator.rs:856
  15: winsafe::gui::native_controls::list_view_items::ListViewItems::add<alloc::string::String>
             at C:\Users\likeqing\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winsafe-0.0.17\src\gui\native_controls\list_view_items.rs:77`

**Comment by rodrigocfd** [comment]
You're probably trying to use `WString` as a buffer without initializing it.

**Comment by QianNangong** [comment]
I have written a piece of code that can reproduce this issue.
```rust
use std::error::Error;

use winsafe::{
    gui::{Horz, ListView, ListViewOpts, Vert, WindowMain, WindowMainOpts},
    prelude::*,
};

#[derive(Clone)]
struct MainWindow {
    window: WindowMain,
    list: ListView,
}

impl MainWindow {
    fn new() -> Self {
        let window = WindowMain::new(WindowMainOpts {
            size: (800, 600),
            ..Default::default()
        });

        let list = ListView::new(
            &window,
            ListViewOpts {
                position: (0, 0),
                size: (800, 600),
                resize_behavior: (Horz::Resize, Vert::Resize),
                columns: vec![("Column 1".to_owned(), 100), ("Column 2".to_owned(), 100)],
                ..Default::default()
            },
        );

        let window = Self { window, list };
        window.events();
        window
    }

    fn events(&self) {
        let list = self.list.clone();
        self.window.on().wm_create(move |_| {
            list.items().add(&["", ""], None);
            Ok(0)
        });
    }
}

fn main() -> Result<(), Box<dyn Error + Send + Sync>> {
    let main_window = MainWindow::new();
    main_window.window.run_main(None)?;
    Ok(())
}
```
